apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
    spec:
      containers:
      - name: hello-world
        image: infrastructureascode/hello-world