---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: ConsulResolver
      name: consul-minidc
      address: myconsul-consul-server.default.svc.cluster.local:8500
      datacenter: minidc

spec:
  type: NodePort
  selector:
    service: ambassador
  ports:
  - port: 80
    targetPort: 8080
    name: http
  - port: 443
    targetPort: 8443
    name: https